name: Pull Request Workflow
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - "*/*"

env:
  NODE_TLS_REJECT_UNAUTHORIZED: 0

jobs:
  build:
    runs-on: rust-stm32-r194
    steps:
      - name: Install SCTB Elpa certificate
        uses: https://gitea.sctbelpa/Public/git-action-ca-certificate-import@v2
        with:
          certificate: ${{ vars.SCTB_ROOT_CERT }}
          certificate-name: "sctb.crt"

      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install crates.io mirror
        run: |
          mkdir -p .cargo/
          echo '${{ vars.CARGO_MIRROR_DEFINE }}' >> .cargo/config.toml
          cat .cargo/config.toml
      
      - name: Build
        run: |
          cargo build --release
